### ISSUE TITLE
Add Brazilian PyLadies Groups

### ISSUE THREAD

**Issue by jtemporal** [jonatasbaldin/python-community-map#51]
There are over 20 PyLadies chapters here in Brazil maybe those can be added too. 

[Here's the site](http://brasil.pyladies.com/locations/)

**Comment by jonatasbaldin** [comment]
Yesssssss! We can try to scrap the site to get the info

**Comment by jonatasbaldin** [comment]
Actually I want to avoid doing scrapping, because I'd like for the people add the communities they belong too, I think it creates a better sense of "putting yourself in the map" of some sorts and also incentivise people to contribute to open source :)

What we could do is to share the map with the PyLadies groups!

**Comment by jtemporal** [comment]
> Any place we could share this more "globally" in the PyLadies community?

Twitter for instance is a good one, we could tag the profiles from around the globe... Also I'll send to the Brazilian pyladies email list... There's also a Slack, I could send there... Do we have a standard message?

**Comment by jonatasbaldin** [comment]
No, I don't :( go from your heart ❤️ we can also tweet, I'm gonna do that!

**Comment by jonatasbaldin** [comment]
Here's the tweet <3 

Gonna close this, if there's more ppl to talk to, you may reopen it!

https://twitter.com/jonatasbaldin/status/1057606111828828160
